AllCops:
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - '**/bin/*'
    - '**/bin/**/*'
    - '**/db/schema.rb'
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/vendor/bundle/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  AutoCorrect: true
