AllCops:
  NewCops: enable
  Exclude:
    - '.git/**/*'
    - '**/bin/*'
    - '**/bin/**/*'
    - '**/db/schema.rb'
    - '**/tmp/**/*'
    - '**/vendor/**/*'
    - '**/vendor/bundle/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  AutoCorrect: true

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'
